version: 0.2
env:
  variables:
    TF_IN_AUTOMATION: "1"
phases:
  install:
    commands:
      - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      - unzip -o /tmp/terraform.zip -d /usr/local/bin
  build:
    commands:
      - cd infra
      - terraform init -input=false
      - terraform workspace select dev || terraform workspace new dev
      - terraform plan -input=false -out=plan-dev.tfplan -var "env=dev"
artifacts:
  files:
    - infra/plan-dev.tfplan
    - infra/.terraform.lock.hcl
    - infra/terraform.tfstate*